name: CordPlanter
version: '1.0.0-R.0-SNAPSHOT'
main: eu.sheepearrr.cordplanter.CordPlanter
description: Make Custom Functionality Easier.
author: Sheepearrr
api-version: '1.21.6'
libraries:
  - com.google.code.gson:gson:2.11.0
